Repository catawiki/rate-limit, pull requests merged in 2022-09, with the labels that each got.

#2 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#4 Fix bug wherein if the topic is provided as a symbol the associated limits are not correctly loaded.
  .gitignore
  lib/rate_limit/throttler.rb
  spec/rate_limit/throttler_spec.rb
Labels: bug

#5 Add `rate-limit.rb` thus fixing automatic requiring of the gem by bundler.
  .rubocop/base.yml
  lib/rate-limit.rb
Labels: bug, bundler

#11 Add Result Class
  lib/rate_limit.rb
  lib/rate_limit/result.rb
  lib/rate_limit/throttler.rb
  spec/rate_limit/config_spec.rb
  spec/rate_limit/configurable_spec.rb
  spec/rate_limit/result_spec.rb
  spec/rate_limit/throttler_spec.rb
Labels: enhancement

#12 Introduce Worker Class
  .rubocop/ruby-3.0.yml
  .rubocop/ruby-3.1.yml
  README.md
  lib/rate_limit.rb
  lib/rate_limit/base.rb
  lib/rate_limit/throttler.rb
  lib/rate_limit/window.rb
  lib/rate_limit/worker.rb
  spec/rate_limit/base_spec.rb
  spec/rate_limit/result_spec.rb
  spec/rate_limit/throttler_spec.rb
  spec/rate_limit/worker_spec.rb
  spec/spec_helper.rb
Labels: documentation, enhancement

#13 Add success/failure callbacks
  README.md
  lib/rate_limit/config.rb
  lib/rate_limit/worker.rb
  spec/rate_limit/config_spec.rb
  spec/rate_limit/result_spec.rb
  spec/rate_limit/throttler_spec.rb
Labels: documentation, enhancement

#17 Update Documentation
  README.md
Labels: documentation
